version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - ADMIN_ID =
      - TOKEN =